### ISSUE TITLE
Sutton's lisp example from Chapter 1.

### ISSUE THREAD

**Issue by mohanr** [gabrieledcjr/TicTacToe#1]
I ported the tictactoe example to haskell. It is https://github.com/mohanr/Reinforcement-Learning-An-Introduction-by-Richard-S.-Sutton-and-Andrew-G.-Barto/blob/master/tictactoe.hs

Player O never wins when I run my code. Player X wins many times. This is determined by the 'nextvalue' function.

Should Player O win too ?

What is the expected output from Sutton's example ? Let's assume we play a 100 times. What rate should this code from his example print ?

       (defun run ()
        (loop repeat 40 do (print (/ (loop repeat 100 sum (game t)) 
                            100.0))))
My rates range from 39 to 47.

**Comment by gabrieledcjr** [comment]
Is player O and player X both RL agents? It's been a while since I've created this code but as I remembered, if both players are competing RL agents, the first player to make a move has a higher chance of winning. The best that the second player can do is to get a draw.

Also, in the newer unpublished book from Sutton, available [online](http://incompleteideas.net/sutton/book/the-book-2nd.html). There is a link to the [codes](https://github.com/ShangtongZhang/reinforcement-learning-an-introduction) from each chapter. It includes the tic tac toe. You can also test that.
